// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKho.Models;

#nullable disable

namespace QuanLyKho.Migrations
{
    [DbContext(typeof(QuanlykhoContext))]
    partial class QuanlykhoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKho.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maPhieuNhap")
                        .IsFixedLength();

                    b.Property<string>("MaThietBi")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maThietBi")
                        .IsFixedLength();

                    b.Property<decimal>("DonGia")
                        .HasColumnType("money")
                        .HasColumnName("donGia");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuNhap", "MaThietBi");

                    b.HasIndex("MaThietBi");

                    b.ToTable("ChiTietPhieuNhap", (string)null);
                });

            modelBuilder.Entity("QuanLyKho.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<decimal>("DonGia")
                        .HasColumnType("money")
                        .HasColumnName("donGia");

                    b.Property<string>("MaPhieuXuat")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maPhieuXuat")
                        .IsFixedLength();

                    b.Property<string>("MaThietBi")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maThietBi")
                        .IsFixedLength();

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("soLuong");

                    b.HasIndex("MaPhieuXuat");

                    b.HasIndex("MaThietBi");

                    b.ToTable("ChiTietPhieuXuat", (string)null);
                });

            modelBuilder.Entity("QuanLyKho.Models.DanhMucThietBi", b =>
                {
                    b.Property<string>("MaDanhMuc")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maDanhMuc")
                        .IsFixedLength();

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("moTa");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tenDanhMuc");

                    b.HasKey("MaDanhMuc")
                        .HasName("PK__DanhMucT__6B0F914CC5325A74");

                    b.ToTable("DanhMucThietBi", (string)null);
                });

            modelBuilder.Entity("QuanLyKho.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MaNhaCungCap")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maNhaCungCap")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("diaChi");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("soDienThoai")
                        .IsFixedLength();

                    b.Property<string>("TenNhaCungCap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenNhaCungCap");

                    b.HasKey("MaNhaCungCap")
                        .HasName("PK__NhaCungC__D0B4D6DE7CFA4E94");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuNhapHang", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maPhieuNhap")
                        .IsFixedLength();

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghiChu");

                    b.Property<string>("MaNguoiDung")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maNguoiDung")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("date")
                        .HasColumnName("ngayNhap");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("money")
                        .HasColumnName("tongTien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaPhieuNhap")
                        .HasName("PK__PhieuNha__E27639348A6EC541");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("PhieuNhapHang", (string)null);
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuXuatHang", b =>
                {
                    b.Property<string>("MaPhieuXuat")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maPhieuXuat")
                        .IsFixedLength();

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghiChu");

                    b.Property<string>("MaNguoiDung")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maNguoiDung")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("date")
                        .HasColumnName("ngayXuat");

                    b.Property<string>("NhanVienXuat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nhanVienXuat");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("money")
                        .HasColumnName("tongTien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaPhieuXuat")
                        .HasName("PK__PhieuXua__2A661240FDB13C39");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("PhieuXuatHang", (string)null);
                });

            modelBuilder.Entity("QuanLyKho.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maNguoiDung")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("email");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("hoVaTen");

                    b.Property<string>("MaVaiTro")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maVaiTro")
                        .IsFixedLength();

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("matKhau");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("soDienThoai")
                        .IsFixedLength();

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("tenDangNhap");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__TaiKhoan__446439EAF452C162");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex(new[] { "Email" }, "UQ_Taikhoan_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__TaiKhoan__59267D4A0852A008")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("QuanLyKho.Models.ThongTinThietBi", b =>
                {
                    b.Property<string>("MaThietBi")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maThietBi")
                        .IsFixedLength();

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("money")
                        .HasColumnName("giaBan");

                    b.Property<string>("MaDanhMuc")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maDanhMuc")
                        .IsFixedLength();

                    b.Property<string>("MaNhaCungCap")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maNhaCungCap")
                        .IsFixedLength();

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("moTa");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("model");

                    b.Property<string>("NhaSanXuat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nhaSanXuat");

                    b.Property<int?>("SoLuongCon")
                        .HasColumnType("int")
                        .HasColumnName("soLuongCon");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tenThietBi");

                    b.Property<string>("ThoiGianBaoHanh")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("thoiGianBaoHanh");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaThietBi")
                        .HasName("PK__ThongTin__DC419B30B30F8AB0");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("ThongTinThietBi", (string)null);
                });

            modelBuilder.Entity("QuanLyKho.Models.VaiTro", b =>
                {
                    b.Property<string>("MaVaiTro")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("maVaiTro")
                        .IsFixedLength();

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("moTa");

                    b.Property<string>("TenVaiTro")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tenVaiTro");

                    b.HasKey("MaVaiTro")
                        .HasName("PK__VaiTro__BFC88AB70E796BBA");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("QuanLyKho.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QuanLyKho.Models.PhieuNhapHang", "MaPhieuNhapNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietPhieuNhap_PhieuNhapHang");

                    b.HasOne("QuanLyKho.Models.ThongTinThietBi", "MaThietBiNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaThietBi")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietPhieuNhap_ThongTinThietBi");

                    b.Navigation("MaPhieuNhapNavigation");

                    b.Navigation("MaThietBiNavigation");
                });

            modelBuilder.Entity("QuanLyKho.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("QuanLyKho.Models.PhieuXuatHang", "MaPhieuXuatNavigation")
                        .WithMany()
                        .HasForeignKey("MaPhieuXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ChiTietPh__maPhi__3D5E1FD2");

                    b.HasOne("QuanLyKho.Models.ThongTinThietBi", "MaThietBiNavigation")
                        .WithMany()
                        .HasForeignKey("MaThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ChiTietPh__maThi__3E52440B");

                    b.Navigation("MaPhieuXuatNavigation");

                    b.Navigation("MaThietBiNavigation");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuNhapHang", b =>
                {
                    b.HasOne("QuanLyKho.Models.TaiKhoan", "MaNguoiDungNavigation")
                        .WithMany("PhieuNhapHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PhieuNhap__maNgu__34C8D9D1");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuXuatHang", b =>
                {
                    b.HasOne("QuanLyKho.Models.TaiKhoan", "MaNguoiDungNavigation")
                        .WithMany("PhieuXuatHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PhieuXuat__maNgu__3B75D760");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("QuanLyKho.Models.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyKho.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan__trangT__286302EC");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("QuanLyKho.Models.ThongTinThietBi", b =>
                {
                    b.HasOne("QuanLyKho.Models.DanhMucThietBi", "MaDanhMucNavigation")
                        .WithMany("ThongTinThietBis")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ThongTinT__maDan__30F848ED");

                    b.HasOne("QuanLyKho.Models.NhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("ThongTinThietBis")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ThongTinT__maNha__31EC6D26");

                    b.Navigation("MaDanhMucNavigation");

                    b.Navigation("MaNhaCungCapNavigation");
                });

            modelBuilder.Entity("QuanLyKho.Models.DanhMucThietBi", b =>
                {
                    b.Navigation("ThongTinThietBis");
                });

            modelBuilder.Entity("QuanLyKho.Models.NhaCungCap", b =>
                {
                    b.Navigation("ThongTinThietBis");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuNhapHang", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QuanLyKho.Models.TaiKhoan", b =>
                {
                    b.Navigation("PhieuNhapHangs");

                    b.Navigation("PhieuXuatHangs");
                });

            modelBuilder.Entity("QuanLyKho.Models.ThongTinThietBi", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QuanLyKho.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
